(cl:defpackage point_cloud_embedder-srv
  (:use )
  (:export
   "GETPOINTCLOUDEMBEDDING"
   "<GETPOINTCLOUDEMBEDDING-REQUEST>"
   "GETPOINTCLOUDEMBEDDING-REQUEST"
   "<GETPOINTCLOUDEMBEDDING-RESPONSE>"
   "GETPOINTCLOUDEMBEDDING-RESPONSE"
  ))

